// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;

import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.DriveTrain;
import edu.wpi.first.wpilibj.Timer;

public class AutonomousDrive2 extends CommandBase {
        // VARIABLE_DECLARATIONS
    private final DriveTrain m_driveTrain;
    /*NetworkTable table = NetworkTableInstance.getDefault().getTable("limelight");
    NetworkTableEntry tv = table.getEntry("tv"); //If target found
    NetworkTableEntry tx = table.getEntry("tx"); //Horizontal Offset From Crosshair To Target (-27 degrees to 27 degrees)
    NetworkTableEntry ty = table.getEntry("ty"); //Vertical Offset From Crosshair To Target (-20.5 degrees to 20.5 degrees)
    NetworkTableEntry ta = table.getEntry("ta"); //Target Area (0% of image to 100% of image)
    double adjustSteering;*/
    Timer autoTimer2 = new Timer();
    double speed, turn;
    double dSpeed;
    int numberOfSeconds;
    //double autoStartTime = 0, autoEndTime = 5;
    //boolean targetFound = false;
        
        //VARIABLE_DECLARATIONS
    /*private XboxController xbox1;
    private Joystick leftJoystick = RobotContainer.getInstance().getJoystickl();
    private Joystick rightJoystick = RobotContainer.getInstance().getJoystickr();
    double speed = -xbox1.getLeftX() * 0.6;
    double turn = xbox1.getRightY() * 0.3;
    double left = speed + turn;
    double right = speed - turn;*/
    // CONSTRUCTORS
    public AutonomousDrive2(DriveTrain subsystem, double driveSpeed, int numSeconds) {
        // CONSTRUCTORS
        // VARIABLE_SETTING
        // VARIABLE_SETTING
        // REQUIRES
        driveSpeed = dSpeed;
        numSeconds = numberOfSeconds;
            m_driveTrain = subsystem;
            addRequirements(m_driveTrain);
        // REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        autoTimer2.reset();
        autoTimer2.start();
        //boolean finish1;
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        speed=-.4;
        turn=0.0;
        
        if(autoTimer2.get() < 4){ //GET CORRECT TIME, make nsure to gfetr off tarmac
            m_driveTrain.drive(speed,turn);
        }
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        m_driveTrain.drive(0.0,0.0);
        
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        if(autoTimer2.get()>4){
            return true;
        }else{
            return false;
        }
    }

    @Override
    public boolean runsWhenDisabled() {
        // DISABLED
        return false;
        // DISABLED
    }
}
