// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;

import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.DriveTrain;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

public class TurnDegrees extends CommandBase {
        // VARIABLE_DECLARATIONS
    private final DriveTrain m_driveTrain;
    /*NetworkTable table = NetworkTableInstance.getDefault().getTable("limelight");
    NetworkTableEntry tv = table.getEntry("tv"); //If target found
    NetworkTableEntry tx = table.getEntry("tx"); //Horizontal Offset From Crosshair To Target (-27 degrees to 27 degrees)
    NetworkTableEntry ty = table.getEntry("ty"); //Vertical Offset From Crosshair To Target (-20.5 degrees to 20.5 degrees)
    NetworkTableEntry ta = table.getEntry("ta"); //Target Area (0% of image to 100% of image)
    double adjustSteering;*/
    int numDegrees;
    Timer degreeTimer = new Timer();
    double speed, turn;
    AnalogGyro gyro1;
        
        //VARIABLE_DECLARATIONS
    // CONSTRUCTORS
    public TurnDegrees(DriveTrain subsystem, int angle) {
        // CONSTRUCTORS
        // VARIABLE_SETTING
        // VARIABLE_SETTING
        // REQUIRES
        angle = numDegrees;
            m_driveTrain = subsystem;
            addRequirements(m_driveTrain);
        // REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        degreeTimer.reset();
        degreeTimer.start();
        gyro1 = m_driveTrain.getGyro();
        gyro1.reset();
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        SmartDashboard.putNumber("Gyro angle",gyro1.getAngle());
        speed=0.0;
        turn=0.5; //turn right (clockwise) and angle increases
        if(gyro1.getAngle()==numDegrees){
            m_driveTrain.drive(speed,turn);
        }else if(degreeTimer.get() < 3){
            m_driveTrain.drive(0.0,0.0);
        }
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        m_driveTrain.drive(0.0,0.0);
        
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        if(degreeTimer.get()>3){
            return true;
        }else{
            return false;
        }
    }

    @Override
    public boolean runsWhenDisabled() {
        // DISABLED
        return false;
        // DISABLED
    }
}
