// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: InstantCommand.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.Constants.IntakeConstants;
import frc.robot.subsystems.Intake;
import edu.wpi.first.wpilibj.Timer;


/**
 *
 */
public class winchDown extends CommandBase {

    // VARIABLE_DECLARATIONS
        private final Intake m_intake;
        Timer mDownTimer = new Timer();
        double armMotorSpeed1=IntakeConstants.armMotorSpeed;
    // VARIABLE_DECLARATIONS
//private JoystickButton b2;
    // CONSTRUCTORS


    public winchDown(Intake subsystem) {


    // CONSTRUCTORS
        // VARIABLE_SETTING

        // VARIABLE_SETTING
        // REQUIRES

        m_intake = subsystem;
        addRequirements(m_intake);

        // REQUIRES
    }

    // Called once when this command runs
    @Override
    public void initialize() {
        mDownTimer.reset();
        mDownTimer.start(); 
    }
    public void execute(){
        m_intake.winchDown(armMotorSpeed1*-1);
        /*if(mDownTimer.get()>6){
            m_intake.winchUp(0);
        }else{
            m_intake.winchUp(-1);
        }*/
    }
    @Override
    public boolean runsWhenDisabled() {
        // DISABLED
        return false;

        // DISABLED
    }
    public void end(boolean Interrupted){
    }
}
